name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do repositório
      - uses: actions/checkout@v4

      # 2. Gera os arquivos da animação usando o token com permissões
      - name: Generate snake files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          # AQUI ESTÁ A MUDANÇA: Usamos o PAT em vez do token padrão
          GITHUB_TOKEN: ${{ secrets.SNAKE_PAT }}

      # 3. Commita e envia os arquivos gerados
      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if ! git diff --staged --quiet; then
            git commit -m "feat: Generate new snake animation"
            git push
          else
            echo "No changes to commit. Snake is up to date."
          fi
