name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    # Adicionamos a permissão de escrita aqui
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}

          # Lista de arquivos a serem gerados.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
