name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Mantemos o token no nível do job para garantir que o 'push' funcione
    env:
      GITHUB_TOKEN: ${{ secrets.SNAKE_PAT }}

    steps:
      # 1. Faz o checkout do repositório
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SNAKE_PAT }}

      # 2. Gera os arquivos da animação
      - name: Generate snake files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        # AQUI ESTÁ A ADIÇÃO CRUCIAL:
        # Forçamos ESTE PASSO a usar o token para LER os seus dados privados.
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_PAT }}

      # 3. Commita e envia os arquivos
      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if ! git diff --staged --quiet; then
            git commit -m "feat: Generate new snake animation"
            git push
          else
            echo "No changes to commit. Snake is up to date."
          fi
